/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocumentRouteImport } from './routes/api/document'
import { Route as ApiCompareRouteImport } from './routes/api/compare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentRoute = ApiDocumentRouteImport.update({
  id: '/api/document',
  path: '/api/document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompareRoute = ApiCompareRouteImport.update({
  id: '/api/compare',
  path: '/api/compare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/compare': typeof ApiCompareRoute
  '/api/document': typeof ApiDocumentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/compare': typeof ApiCompareRoute
  '/api/document': typeof ApiDocumentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/compare': typeof ApiCompareRoute
  '/api/document': typeof ApiDocumentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/compare' | '/api/document'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/compare' | '/api/document'
  id: '__root__' | '/' | '/api/compare' | '/api/document'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCompareRoute: typeof ApiCompareRoute
  ApiDocumentRoute: typeof ApiDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document': {
      id: '/api/document'
      path: '/api/document'
      fullPath: '/api/document'
      preLoaderRoute: typeof ApiDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compare': {
      id: '/api/compare'
      path: '/api/compare'
      fullPath: '/api/compare'
      preLoaderRoute: typeof ApiCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCompareRoute: ApiCompareRoute,
  ApiDocumentRoute: ApiDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
